In [13]:
import numpy as np

#### 0D tensor/ scalar

In [14]:
a = np.array(1)
print(a)
a

1


array(1)

In [15]:
print(a.shape)
a.ndim

()


0

#### 1d tensor / vector

In [16]:
a = np.array([1,2,3,4])
print(a)
a

[1 2 3 4]


array([1, 2, 3, 4])

In [17]:
print(a.shape)
a.ndim


(4,)


1

#### 2d tensor / matrices

In [19]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
print(a.shape)
a.ndim

(2, 3)


2

#### nd tensor / tensor

In [23]:
a = np.array([[[1,2,3],[4,5,6]]])
print(a)

[[[1 2 3]
  [4 5 6]]]


In [25]:
print(a.shape)
a.ndim

(1, 2, 3)


3